sudo: required
language: python

services:
  - docker

python:
    - 3.6

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=

install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install -r requirements-dev.txt
    - pip install codecov

script:
    - make flake
    - make docker_build
    - make docker_cov

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    - codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: ZYJum3shkWaQ0vgtpwWwY5Qn04/Sku5Jmt3x/XIfQxaWATVbGEnRgJSmxrf5oGqCkIW65cIbKrycZ9KtlVt/zbjwyFsDZDtEd2eqhy1DmgyGlemwajgShdSC2cZsb0fUSJKeV+ngAsirAC9UhTJk6Fi0M9QXSwcqFxj9OVny0z9wr02EsQ+bJM8gx9B9M63vMJ8C+AkG8ktPQiyPkEXN1YxyrM0xfZ7IdR5l28VbgAvyT5HbRYmVvMom7Q6+N+QwRU4+/RF8mGxiOhjBURInwB4m3ta0GAZ69Yop8So+8cLzN4s7nCCAr8htrYm6cR+e9T9CArAulVBDwQwQaEVLnA2xqt6i9lI2dmIxotPVxoJzS4YeoayNzCY0ty5f1b7JWPeLyJtvQ6NW18+qtuvBrqWyyFlaovF+iGb3auzAKO26tZjGKIBD0VE+LXpvv29R3ocdergrcfVc/ZEQ0/Kq/0DnfmKyChlFqr68JFrpuCAZaZklHSWFpw4oZqKFjBY2ei/lwtOzDiBL0bwd7ZLec9606oIY5DnhOas3DmSohDTRaFiv0JG1cQRFyz2HU2oOY1jvBi5WrN/Ak+tVAgiVEqlaZ7Gdq6y377+SEUah/35rSug5gGZdNrQViX+P2M+R5JEd5ESJhJAafMr7N9oSahmF/1/mP1jxyWE7UIFkyHY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: aio-libs/aioodbc
    all_branches: true
    python: 3.6
